/* Repacks pcb.obj into pcb.bin, which is what the page actually loads.
 *
 *   node lab/model/pack.mjs
 *
 * Run it whenever pcb.obj changes and commit both. The OBJ stays the source of
 * truth — it is the thing the CAD export produced and the thing every note in
 * NOTES.md is measured against — and pcb.bin is a derived artefact, in the repo
 * for the same reason a minified bundle is.
 *
 * Why this exists: the OBJ is 6.6 MB, 1.62 MB gzipped, and takes 152 ms to parse
 * in OBJLoader, measured in node on this machine. That parse is 152 ms of the
 * main thread before a single triangle exists, on the page whose first screen is
 * the model. The bin is a header, a name table, a run table and two typed
 * arrays; loading it is three DataView reads and two `new Float32Array(buffer,
 * offset, length)`, which is not a parse at all.
 *
 * Every triangle survives, which was the explicit call — no decimation, no weld,
 * no reorder. Three things are dropped and each is worth defending:
 *
 *   The normals. All 18,504 of them, and this is the change that makes the
 *   format small. The page recomputes normals per face immediately after cull()
 *   because the exporter's are not unit length — see NOTES.md rev 15 — so every
 *   byte of `vn` in that file is read, parsed, uploaded and then thrown away.
 *
 *   The texture coordinates. There are none: 0 `vt` lines. The board's UVs are
 *   generated by planarUV() from board millimetres.
 *
 *   The material *definitions*. pcb.mtl is 29 short records and still loads
 *   through MTLLoader, because the page's upgrade() reads each Kd to decide what
 *   the material is. The bin carries only the names, in the order the runs
 *   reference them.
 *
 * Positions stay float32 rather than being quantised to int16 against the
 * bounding box, which would have halved them again. 25 mm over 65,535 steps is
 * 0.38 µm and that is plenty for anything you can see — but this model has
 * thousands of tessellator slivers a micron or two across, inside flat faces,
 * and quantisation collapses some fraction of those to zero area. A zero-area
 * triangle has no normal, and per-face shading turns it black. The precision is
 * not needed for geometry; it is needed to keep degenerate triangles from
 * becoming degenerate in a way that shows.
 *
 * Layout, little-endian throughout:
 *
 *   u32   magic 'IMPB'
 *   u32   version
 *   u32   vertex count
 *   u32   triangle count
 *   u32   run count            one per usemtl run, in file order
 *   u32   name count
 *   ...   names: u8 length + ASCII each, then padded to a 4-byte boundary
 *   ...   runs: u32 first triangle, u32 triangle count, u32 name index
 *   f32   positions, 3 per vertex
 *   u16   indices, 3 per triangle
 *
 * Indices are u16, which holds because this model has 27,420 vertices. The
 * writer asserts it rather than assuming it: a re-export that crosses 65,536
 * needs a version 2 with u32 indices, and silently wrapping would be a very
 * confusing bug.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, 'pcb.obj'), 'utf8');

const pos = [];            // flat xyz
const tris = [];           // flat vertex indices
const names = [];          // material names, first-seen order
const nameOf = new Map();  // name -> index
const runs = [];           // { first, count, name }
let run = null;

for (const line of src.split('\n')) {
  if (line.startsWith('v ')) {
    const p = line.split(/\s+/);
    pos.push(+p[1], +p[2], +p[3]);
  } else if (line.startsWith('usemtl ')) {
    const name = line.slice(7).trim();
    if (!nameOf.has(name)) { nameOf.set(name, names.length); names.push(name); }
    /* One run per usemtl, even two in a row naming the same material. The page's
       groups have to line up with the export's runs because every note about
       "mtl14 is the sensor package" is a statement about this ordering. */
    run = { first: tris.length / 3, count: 0, name: nameOf.get(name) };
    runs.push(run);
  } else if (line.startsWith('f ')) {
    /* `f v//vn`, and only the v matters. Fanned, though every face in this
       export is already a triangle — a quad from a future re-export should not
       silently lose a corner. */
    const parts = line.trim().split(/\s+/).slice(1);
    const idx = parts.map(t => parseInt(t, 10) - 1);
    for (let k = 1; k + 1 < idx.length; k++) {
      tris.push(idx[0], idx[k], idx[k + 1]);
      if (run) run.count++;
    }
  }
}

const vertCount = pos.length / 3;
const triCount = tris.length / 3;
if (vertCount > 65536) {
  throw new Error(`${vertCount} vertices will not fit u16 indices — bump the format version`);
}

/* Runs of zero triangles happen when a usemtl is followed immediately by
   another; they would be harmless as empty groups but there is no reason to
   write them. */
const kept = runs.filter(r => r.count > 0);

const nameBytes = names.reduce((n, s) => n + 1 + s.length, 0);
const namePad = (4 - (nameBytes % 4)) % 4;
const head = 24;
const runsAt = head + nameBytes + namePad;
const posAt = runsAt + kept.length * 12;
const idxAt = posAt + vertCount * 12;
const total = idxAt + triCount * 6;

const buf = Buffer.alloc(total);
buf.write('IMPB', 0, 'ascii');
buf.writeUInt32LE(1, 4);
buf.writeUInt32LE(vertCount, 8);
buf.writeUInt32LE(triCount, 12);
buf.writeUInt32LE(kept.length, 16);
buf.writeUInt32LE(names.length, 20);

let o = head;
for (const n of names) {
  buf.writeUInt8(n.length, o++);
  buf.write(n, o, 'ascii');
  o += n.length;
}

o = runsAt;
for (const r of kept) {
  buf.writeUInt32LE(r.first, o);
  buf.writeUInt32LE(r.count, o + 4);
  buf.writeUInt32LE(r.name, o + 8);
  o += 12;
}

o = posAt;
for (let i = 0; i < pos.length; i++) { buf.writeFloatLE(pos[i], o); o += 4; }
o = idxAt;
for (let i = 0; i < tris.length; i++) { buf.writeUInt16LE(tris[i], o); o += 2; }

writeFileSync(join(here, 'pcb.bin'), buf);

const kb = n => (n / 1024).toFixed(0) + ' KB';
console.log(`pcb.bin  ${kb(total)}  ` +
            `${vertCount} vertices, ${triCount} triangles, ` +
            `${kept.length} runs over ${names.length} materials`);
console.log(`         was ${kb(Buffer.byteLength(src))} of OBJ`);
